## CURL 
- Using curl in the command line:<br> 
`curl -i google.com`
- Extract all the books:<br>  
`curl http://andrewbeatty1.pythonanywhere.com/books`
- Extract book 17:<br>
`curl http://andrewbeatty1.pythonanywhere.com/books/17`
- Create a book:<br>
````
curl -H "Content-Type:application/json" -X POST -d
"{\"title\":\"xxx\",\"author\":\"xxx\",\"price\":3000}"
http://andrewbeatty1.pythonanywhere.com/books
````
- Update the price of the book:<br>
````
curl -H "Content-Type:application/json" -X PUT
-d "{\"price\":2000}"
http://andrewbeatty1.pythonanywhere.com/books/???
````
- Delete the book: <br>
`curl -X DELETE http://andrewbeatty1.pythonanywhere.com/books/???`

****************************

## REQUESTS
**************************

In [64]:
## LIBRARIES
import requests
import importlib
import lab4_requests
import cso_dao
import json

In [ ]:
url = "http://andrewbeatty1.pythonanywhere.com/books"
response = requests.get(url)
print (response.text)
print (response.json())

[{"author":"xxx","id":545,"price":3000,"title":"xxx"},{"author":"ED","id":546,"price":72,"title":"Add your name in the body"},{"author":"Andrew B","id":549,"price":888,"title":"test"},{"author":"Douglas Adams","id":550,"price":42,"title":"The Hitchhiker's Guide to the Galaxy"},{"author":"Quinn","id":557,"price":200,"title":"Projects Time"},{"author":"Kwon","id":561,"price":2001,"title":"Python Hurts"},{"author":"Patrick","id":562,"price":1000002,"title":"Averages are Evil"},{"author":"JRR Tolkien","id":566,"price":500,"title":"Lord of the Rings "},{"author":"unknown","id":567,"price":100,"title":"the best book"},{"author":"","id":569,"price":0,"title":""},{"author":"Paulo Coelho","id":571,"price":26,"title":"The Alchemist"},{"author":"","id":572,"price":0,"title":""},{"author":"Paulo Coelho","id":573,"price":26,"title":"The Alchemist"},{"author":"Paulo Coelho","id":574,"price":27,"title":"Veronika Decides to Die"},{"author":"xxx","id":575,"price":5000,"title":"delmein class"},{"author":"andrew","id":576,"price":1234,"title":"by curl"},{"author":"xxx","id":580,"price":3000,"title":"xxx"},{"author":"xxx","id":597,"price":3000,"title":"xxx"}]

[{'author': 'xxx', 'id': 545, 'price': 3000, 'title': 'xxx'}, {'author': 'ED', 'id': 546, 'price': 72, 'title': 'Add your name in the body'}, {'author': 'Andrew B', 'id': 549, 'price': 888, 'title': 'test'}, {'author': 'Douglas Adams', 'id': 550, 'price': 42, 'title': "The Hitchhiker's Guide to the Galaxy"}, {'author': 'Quinn', 'id': 557, 'price': 200, 'title': 'Projects Time'}, {'author': 'Kwon', 'id': 561, 'price': 2001, 'title': 'Python Hurts'}, {'author': 'Patrick', 'id': 562, 'price': 1000002, 'title': 'Averages are Evil'}, {'author': 'JRR Tolkien', 'id': 566, 'price': 500, 'title': 'Lord of the Rings '}, {'author': 'unknown', 'id': 567, 'price': 100, 'title': 'the best book'}, {'author': '', 'id': 569, 'price': 0, 'title': ''}, {'author': 'Paulo Coelho', 'id': 571, 'price': 26, 'title': 'The Alchemist'}, {'author': '', 'id': 572, 'price': 0, 'title': ''}, {'author': 'Paulo Coelho', 'id': 573, 'price': 26, 'title': 'The Alchemist'}, {'author': 'Paulo Coelho', 'id': 574, 'price': 27, 'title': 'Veronika Decides to Die'}, {'author': 'xxx', 'id': 575, 'price': 5000, 'title': 'delmein class'}, {'author': 'andrew', 'id': 576, 'price': 1234, 'title': 'by curl'}, {'author': 'xxx', 'id': 580, 'price': 3000, 'title': 'xxx'}, {'author': 'xxx', 'id': 597, 'price': 3000, 'title': 'xxx'}]

In [46]:
importlib.reload(lab4_requests)
lab4_requests.readbooks("http://andrewbeatty1.pythonanywhere.com/books")

[{'author': 'xxx', 'id': 545, 'price': 3000, 'title': 'xxx'},
 {'author': 'ED',
  'id': 546,
  'price': 72,
  'title': 'Add your name in the body'},
 {'author': 'Andrew B', 'id': 549, 'price': 888, 'title': 'test'},
 {'author': 'Douglas Adams',
  'id': 550,
  'price': 42,
  'title': "The Hitchhiker's Guide to the Galaxy"},
 {'author': 'Quinn', 'id': 557, 'price': 200, 'title': 'Projects Time'},
 {'author': 'Kwon', 'id': 561, 'price': 2001, 'title': 'Python Hurts'},
 {'author': 'Patrick',
  'id': 562,
  'price': 1000002,
  'title': 'Averages are Evil'},
 {'author': 'JRR Tolkien',
  'id': 566,
  'price': 500,
  'title': 'Lord of the Rings '},
 {'author': 'unknown', 'id': 567, 'price': 100, 'title': 'the best book'},
 {'author': '', 'id': 569, 'price': 0, 'title': ''},
 {'author': 'Paulo Coelho', 'id': 571, 'price': 26, 'title': 'The Alchemist'},
 {'author': '', 'id': 572, 'price': 0, 'title': ''},
 {'author': 'Paulo Coelho', 'id': 573, 'price': 26, 'title': 'The Alchemist'},
 {'author': 'Paulo Coelho',
  'id': 574,
  'price': 27,
  'title': 'Veronika Decides to Die'},
 {'author': 'xxx', 'id': 575, 'price': 5000, 'title': 'delmein class'},
 {'author': 'andrew', 'id': 576, 'price': 1234, 'title': 'by curl'},
 {'author': 'xxx', 'id': 580, 'price': 3000, 'title': 'xxx'},
 {'author': 'xxx', 'id': 597, 'price': 3000, 'title': 'xxx'},
 {'author': 'Tamsyn Muir', 'id': 601, 'price': 2, 'title': 'Gideon the Ninth'}]

In [44]:
importlib.reload(lab4_requests)
lab4_requests.readbookid("http://andrewbeatty1.pythonanywhere.com/books", 550)

{'author': 'Douglas Adams',
 'id': 550,
 'price': 42,
 'title': "The Hitchhiker's Guide to the Galaxy"}

In [45]:
importlib.reload(lab4_requests)
lab4_requests.createbook("http://andrewbeatty1.pythonanywhere.com/books",
                         {'author': 'Tamsyn Muir', 'price': 2, 'title': "Gideon the Ninth"})

{'author': 'Tamsyn Muir', 'id': 601, 'price': 2, 'title': 'Gideon the Ninth'}

In [ ]:
importlib.reload(lab4_requests)
lab4_requests.updatebook("http://andrewbeatty1.pythonanywhere.com/books", {'price': 21}, 601)

In [ ]:
importlib.reload(lab4_requests)
lab4_requests.deletebook("http://andrewbeatty1.pythonanywhere.com/books", 600)

{'done': True}

In [51]:
importlib.reload(lab4_requests)
lab4_requests.extract_mean_price("http://andrewbeatty1.pythonanywhere.com/books")

48691.333333333336

In [ ]:
#CSO DAO
url= "https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/FP001/JSON-stat/2.0/en"
response = requests.get(url)
list = response.json()

with open("cso.json", "wt") as f:
    f.write(json.dumps(list))

In [164]:
id = list["id"]
dimension = list["dimension"]
size = list["size"]
value = list["value"]

size

[4, 1, 3, 27]

In [155]:
for i in range(0, size[0]):
    currentid = id[0]
    index = dimension[currentid]["category"]["index"][i]
    label = dimension[currentid]["category"]["label"][index]
    print(index, label)

FP001C01 Population 2016
FP001C02 Population 2022
FP001C03 Actual change since previous census
FP001C04 Percentage change since previous census

In [165]:
for i in range(0, size[1]):
    currentid = id[1]
    index = dimension[currentid]["category"]["index"][i]
    label = dimension[currentid]["category"]["label"][index]
    print(index, label)

2022 2022

In [153]:
for i in range(0, size[2]):
    currentid = id[2]
    index = dimension[currentid]["category"]["index"][i]
    label = dimension[currentid]["category"]["label"][index]
    print(index, label)

- Both sexes
1 Male
2 Female

In [159]:
for i in range(0, size[3]):
    currentid = id[3]
    index = dimension[currentid]["category"]["index"][i]
    label = dimension[currentid]["category"]["label"][index]
    print(index, label)

IE0 Ireland
2ae19629-143d-13a3-e055-000000000001 Co. Carlow
2ae19629-1448-13a3-e055-000000000001 Co. Cavan
2ae19629-1450-13a3-e055-000000000001 Co. Clare
2ae19629-1451-13a3-e055-000000000001 Co. Cork
2ae19629-1452-13a3-e055-000000000001 Co. Donegal
2ae19629-144f-13a3-e055-000000000001 Co. Dublin
2ae19629-1453-13a3-e055-000000000001 Co. Galway
2ae19629-1454-13a3-e055-000000000001 Co. Kerry
2ae19629-1455-13a3-e055-000000000001 Co. Kildare
2ae19629-1456-13a3-e055-000000000001 Co. Kilkenny
2ae19629-143e-13a3-e055-000000000001 Co. Laois
2ae19629-143f-13a3-e055-000000000001 Co. Leitrim
2ae19629-1440-13a3-e055-000000000001 Co. Limerick
2ae19629-1441-13a3-e055-000000000001 Co. Longford
2ae19629-1442-13a3-e055-000000000001 Co. Louth
2ae19629-1443-13a3-e055-000000000001 Co. Mayo
2ae19629-1444-13a3-e055-000000000001 Co. Meath
2ae19629-1445-13a3-e055-000000000001 Co. Monaghan
2ae19629-1446-13a3-e055-000000000001 Co. Offaly
2ae19629-1447-13a3-e055-000000000001 Co. Roscommon
2ae19629-1449-13a3-e055-000000000001 Co. Sligo
2ae19629-144a-13a3-e055-000000000001 Co. Tipperary
2ae19629-144b-13a3-e055-000000000001 Co. Waterford
2ae19629-144c-13a3-e055-000000000001 Co. Westmeath
2ae19629-144d-13a3-e055-000000000001 Co. Wexford
2ae19629-144e-13a3-e055-000000000001 Co. Wicklow

In [180]:
results = {}

for j in range(0, 4):
    print(f"j={j}")
    for i in range(0, size[j]):
        currentid = id[j]
        index = dimension[currentid]["category"]["index"][i]
        label = dimension[currentid]["category"]["label"][index]
        print(f"{i}:{index}: {label}")

j=0
0:FP001C01: Population 2016
1:FP001C02: Population 2022
2:FP001C03: Actual change since previous census
3:FP001C04: Percentage change since previous census
j=1
0:2022: 2022
j=2
0:-: Both sexes
1:1: Male
2:2: Female
j=3
0:IE0: Ireland
1:2ae19629-143d-13a3-e055-000000000001: Co. Carlow
2:2ae19629-1448-13a3-e055-000000000001: Co. Cavan
3:2ae19629-1450-13a3-e055-000000000001: Co. Clare
4:2ae19629-1451-13a3-e055-000000000001: Co. Cork
5:2ae19629-1452-13a3-e055-000000000001: Co. Donegal
6:2ae19629-144f-13a3-e055-000000000001: Co. Dublin
7:2ae19629-1453-13a3-e055-000000000001: Co. Galway
8:2ae19629-1454-13a3-e055-000000000001: Co. Kerry
9:2ae19629-1455-13a3-e055-000000000001: Co. Kildare
10:2ae19629-1456-13a3-e055-000000000001: Co. Kilkenny
11:2ae19629-143e-13a3-e055-000000000001: Co. Laois
12:2ae19629-143f-13a3-e055-000000000001: Co. Leitrim
13:2ae19629-1440-13a3-e055-000000000001: Co. Limerick
14:2ae19629-1441-13a3-e055-000000000001: Co. Longford
15:2ae19629-1442-13a3-e055-000000000001: Co. Louth
16:2ae19629-1443-13a3-e055-000000000001: Co. Mayo
17:2ae19629-1444-13a3-e055-000000000001: Co. Meath
18:2ae19629-1445-13a3-e055-000000000001: Co. Monaghan
19:2ae19629-1446-13a3-e055-000000000001: Co. Offaly
20:2ae19629-1447-13a3-e055-000000000001: Co. Roscommon
21:2ae19629-1449-13a3-e055-000000000001: Co. Sligo
22:2ae19629-144a-13a3-e055-000000000001: Co. Tipperary
23:2ae19629-144b-13a3-e055-000000000001: Co. Waterford
24:2ae19629-144c-13a3-e055-000000000001: Co. Westmeath
25:2ae19629-144d-13a3-e055-000000000001: Co. Wexford
26:2ae19629-144e-13a3-e055-000000000001: Co. Wicklow

In [66]:
cso_dao.getAllAsFile("FP001")

In [67]:
cso_dao.getAll("FP001")

{'class': 'dataset',
 'dimension': {'STATISTIC': {'category': {'index': ['FP001C01',
     'FP001C02',
     'FP001C03',
     'FP001C04'],
    'label': {'FP001C01': 'Population 2016',
     'FP001C02': 'Population 2022',
     'FP001C03': 'Actual change since previous census',
     'FP001C04': 'Percentage change since previous census'},
    'unit': {'FP001C01': {'decimals': 0, 'label': 'Number', 'position': 'end'},
     'FP001C02': {'decimals': 0, 'label': 'Number', 'position': 'end'},
     'FP001C03': {'decimals': 0, 'label': 'Number', 'position': 'end'},
     'FP001C04': {'decimals': 1, 'label': '%', 'position': 'end'}}},
   'label': 'Statistic'},
  'TLIST(A1)': {'category': {'index': ['2022'], 'label': {'2022': '2022'}},
   'label': 'CensusYear'},
  'C02199V02655': {'category': {'index': ['-', '1', '2'],
    'label': {'-': 'Both sexes', '1': 'Male', '2': 'Female'}},
   'label': 'Sex'},
  'C03788V04538': {'category': {'index': ['IE0',
     '2ae19629-143d-13a3-e055-000000000001',
     '2ae19629-1448-13a3-e055-000000000001',
     '2ae19629-1450-13a3-e055-000000000001',
     '2ae19629-1451-13a3-e055-000000000001',
     '2ae19629-1452-13a3-e055-000000000001',
     '2ae19629-144f-13a3-e055-000000000001',
     '2ae19629-1453-13a3-e055-000000000001',
     '2ae19629-1454-13a3-e055-000000000001',
     '2ae19629-1455-13a3-e055-000000000001',
     '2ae19629-1456-13a3-e055-000000000001',
     '2ae19629-143e-13a3-e055-000000000001',
     '2ae19629-143f-13a3-e055-000000000001',
     '2ae19629-1440-13a3-e055-000000000001',
     '2ae19629-1441-13a3-e055-000000000001',
     '2ae19629-1442-13a3-e055-000000000001',
     '2ae19629-1443-13a3-e055-000000000001',
     '2ae19629-1444-13a3-e055-000000000001',
     '2ae19629-1445-13a3-e055-000000000001',
     '2ae19629-1446-13a3-e055-000000000001',
     '2ae19629-1447-13a3-e055-000000000001',
     '2ae19629-1449-13a3-e055-000000000001',
     '2ae19629-144a-13a3-e055-000000000001',
     '2ae19629-144b-13a3-e055-000000000001',
     '2ae19629-144c-13a3-e055-000000000001',
     '2ae19629-144d-13a3-e055-000000000001',
     '2ae19629-144e-13a3-e055-000000000001'],
    'label': {'IE0': 'Ireland',
     '2ae19629-143d-13a3-e055-000000000001': 'Co. Carlow',
     '2ae19629-1448-13a3-e055-000000000001': 'Co. Cavan',
     '2ae19629-1450-13a3-e055-000000000001': 'Co. Clare',
     '2ae19629-1451-13a3-e055-000000000001': 'Co. Cork',
     '2ae19629-1452-13a3-e055-000000000001': 'Co. Donegal',
     '2ae19629-144f-13a3-e055-000000000001': 'Co. Dublin',
     '2ae19629-1453-13a3-e055-000000000001': 'Co. Galway',
     '2ae19629-1454-13a3-e055-000000000001': 'Co. Kerry',
     '2ae19629-1455-13a3-e055-000000000001': 'Co. Kildare',
     '2ae19629-1456-13a3-e055-000000000001': 'Co. Kilkenny',
     '2ae19629-143e-13a3-e055-000000000001': 'Co. Laois',
     '2ae19629-143f-13a3-e055-000000000001': 'Co. Leitrim',
     '2ae19629-1440-13a3-e055-000000000001': 'Co. Limerick',
     '2ae19629-1441-13a3-e055-000000000001': 'Co. Longford',
     '2ae19629-1442-13a3-e055-000000000001': 'Co. Louth',
     '2ae19629-1443-13a3-e055-000000000001': 'Co. Mayo',
     '2ae19629-1444-13a3-e055-000000000001': 'Co. Meath',
     '2ae19629-1445-13a3-e055-000000000001': 'Co. Monaghan',
     '2ae19629-1446-13a3-e055-000000000001': 'Co. Offaly',
     '2ae19629-1447-13a3-e055-000000000001': 'Co. Roscommon',
     '2ae19629-1449-13a3-e055-000000000001': 'Co. Sligo',
     '2ae19629-144a-13a3-e055-000000000001': 'Co. Tipperary',
     '2ae19629-144b-13a3-e055-000000000001': 'Co. Waterford',
     '2ae19629-144c-13a3-e055-000000000001': 'Co. Westmeath',
     '2ae19629-144d-13a3-e055-000000000001': 'Co. Wexford',
     '2ae19629-144e-13a3-e055-000000000001': 'Co. Wicklow'}},
   'label': 'County',
   'link': {'enclosure': [{'type': 'application/geo+json',
      'href': 'https://ws.cso.ie/public/api.static/PxStat.Data.GeoMap_API.Read/893a6eb4f4a6f907410396ec8d8b738b'}]}}},
 'extension': {'matrix': 'FP001',
  'reasons': ['Planned Routine Revision'],
  'language': {'code': 'en', 'name': 'English'},
  'elimination': {'C02199V02655': '-', 'C03788V04538': 'IE0'},
  'contact': {'name': 'Bernie Casey',
   'email': 'census@cso.ie',
   'phone': '(+353) 1 895 1460'},
  'subject': {'code': 76, 'value': 'Census 2022'},
  'product': {'code': 'C2022SR', 'value': 'Census 2022 Summary Results'},
  'official': True,
  'copyright': {'name': 'Central Statistics Office, Ireland',
   'code': 'CSO',
   'href': 'https://www.cso.ie/'},
  'exceptional': False,
  'reservation': False,
  'archive': True,
  'experimental': False,
  'analytical': False},
 'href': 'https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/FP001/PX/2013/en',
 'id': ['STATISTIC', 'TLIST(A1)', 'C02199V02655', 'C03788V04538'],
 'label': 'Preliminary Actual and Percentage Change in Population 2016 - 2022',
 'link': {'alternate': [{'type': 'text/csv',
    'href': 'https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/FP001/CSV/1.0/en'},
   {'type': 'application/json',
    'href': 'https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/FP001/JSON-stat/2.0/en'},
   {'type': 'application/json',
    'href': 'https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/FP001/JSON-stat/1.0/en'},
   {'type': 'application/base64',
    'href': 'https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/FP001/XLSX/2007/en'}]},
 'note': ['Figures for 2022 are preliminary.',
  'For more information, please go to the [url=https://www.cso.ie/en/statistics/population/censusofpopulation2022/]statistical release page[/url] on our website.'],
 'role': {'geo': ['C03788V04538'],
  'metric': ['STATISTIC'],
  'time': ['TLIST(A1)']},
 'size': [4, 1, 3, 27],
 'updated': '2022-06-27T11:00:00Z',
 'value': [4761865.0,
  56932.0,
  76176.0,
  118817.0,
  542868.0,
  159192.0,
  1347359.0,
  258058.0,
  147707.0,
  222504.0,
  99232.0,
  84697.0,
  32044.0,
  194899.0,
  40873.0,
  128884.0,
  130507.0,
  195044.0,
  61386.0,
  77961.0,
  64544.0,
  65535.0,
  159553.0,
  116176.0,
  88770.0,
  149722.0,
  142425.0,
  2354428.0,
  28465.0,
  38330.0,
  58785.0,
  268675.0,
  79022.0,
  658371.0,
  127663.0,
  73055.0,
  110546.0,
  49533.0,
  42811.0,
  16064.0,
  97340.0,
  20587.0,
  63633.0,
  65047.0,
  96776.0,
  30866.0,
  38838.0,
  32377.0,
  32365.0,
  79668.0,
  57651.0,
  44082.0,
  73722.0,
  70156.0,
  2407437.0,
  28467.0,
  37846.0,
  60032.0,
  274193.0,
  80170.0,
  688988.0,
  130395.0,
  74652.0,
  111958.0,
  49699.0,
  41886.0,
  15980.0,
  97559.0,
  20286.0,
  65251.0,
  65460.0,
  98268.0,
  30520.0,
  39123.0,
  32167.0,
  33170.0,
  79885.0,
  58525.0,
  44688.0,
  76000.0,
  72269.0,
  5123536.0,
  61931.0,
  81201.0,
  127419.0,
  581231.0,
  166321.0,
  1450701.0,
  276451.0,
  155258.0,
  246977.0,
  103685.0,
  91657.0,
  35087.0,
  205444.0,
  46634.0,
  139100.0,
  137231.0,
  220296.0,
  64832.0,
  82668.0,
  69995.0,
  69819.0,
  167661.0,
  127085.0,
  95840.0,
  163527.0,
  155485.0,
  2529936.0,
  30859.0,
  40809.0,
  62686.0,
  287002.0,
  82375.0,
  708998.0,
  136318.0,
  76692.0,
  122650.0,
  51608.0,
  46218.0,
  17518.0,
  102221.0,
  23355.0,
  68594.0,
  67970.0,
  109833.0,
  32661.0,
  41399.0,
  35062.0,
  34359.0,
  83465.0,
  62821.0,
  47522.0,
  80599.0,
  76342.0,
  2593600.0,
  31072.0,
  40392.0,
  64733.0,
  294229.0,
  83946.0,
  741703.0,
  140133.0,
  78566.0,
  124327.0,
  52077.0,
  45439.0,
  17569.0,
  103223.0,
  23279.0,
  70506.0,
  69261.0,
  110463.0,
  32171.0,
  41269.0,
  34933.0,
  35460.0,
  84196.0,
  64264.0,
  48318.0,
  82928.0,
  79143.0,
  361671.0,
  4999.0,
  5025.0,
  8602.0,
  38363.0,
  7129.0,
  103342.0,
  18393.0,
  7551.0,
  24473.0,
  4453.0,
  6960.0,
  3043.0,
  10545.0,
  5761.0,
  10216.0,
  6724.0,
  25252.0,
  3446.0,
  4707.0,
  5451.0,
  4284.0,
  8108.0,
  10909.0,
  7070.0,
  13805.0,
  13060.0,
  175508.0,
  2394.0,
  2479.0,
  3901.0,
  18327.0,
  3353.0,
  50627.0,
  8655.0,
  3637.0,
  12104.0,
  2075.0,
  3407.0,
  1454.0,
  4881.0,
  2768.0,
  4961.0,
  2923.0,
  13057.0,
  1795.0,
  2561.0,
  2685.0,
  1994.0,
  3797.0,
  5170.0,
  3440.0,
  6877.0,
  6186.0,
  186163.0,
  2605.0,
  2546.0,
  4701.0,
  20036.0,
  3776.0,
  52715.0,
  9738.0,
  3914.0,
  12369.0,
  2378.0,
  3553.0,
  1589.0,
  5664.0,
  2993.0,
  5255.0,
  3801.0,
  12195.0,
  1651.0,
  2146.0,
  2766.0,
  2290.0,
  4311.0,
  5739.0,
  3630.0,
  6928.0,
  6874.0,
  7.6,
  8.78,
  6.6,
  7.24,
  7.07,
  4.48,
  7.67,
  7.13,
  5.11,
  11.0,
  4.49,
  8.22,
  9.5,
  5.41,
  14.09,
  7.93,
  5.15,
  12.95,
  5.61,
  6.04,
  8.45,
  6.54,
  5.08,
  9.39,
  7.96,
  9.22,
  9.17,
  7.45,
  8.41,
  6.47,
  6.64,
  6.82,
  4.24,
  7.69,
  6.78,
  4.98,
  10.95,
  4.19,
  7.96,
  9.05,
  5.01,
  13.45,
  7.8,
  4.49,
  13.49,
  5.82,
  6.59,
  8.29,
  6.16,
  4.77,
  8.97,
  7.8,
  9.33,
  8.82,
  7.73,
  9.15,
  6.73,
  7.83,
  7.31,
  4.71,
  7.65,
  7.47,
  5.24,
  11.05,
  4.78,
  8.48,
  9.94,
  5.81,
  14.75,
  8.05,
  5.81,
  12.41,
  5.41,
  5.49,
  8.6,
  6.9,
  5.4,
  9.81,
  8.12,
  9.12,
  9.51],
 'version': '2.0'}